version: "3.8"
services:
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend:/app
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - webnet

  backend:
    build: ./backend/
    volumes:
      - ./backend:/app
    ports:
      - "5100:5100"
    networks:
      - webnet

networks:
  webnet:
