version: "3.8"
services:
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend:/app
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - webnet
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend/
    volumes:
      - ./backend:/app
    ports:
      - "5100:5100"
    depends_on:
      - db
    networks:
      - webnet
    env_file:
      - ./backend/.env

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    networks:
      - webnet

networks:
  webnet:
